#!/usr/bin/env ruby -wU

require 'highline'
require 'pry'

BALLS = [
   { number:  1,
     nickname: "Kelly's Eye",
     notes: %{The pun is military slang; possibly a reference to Ned Kelly, from Ned Kelly's helmet, the eye slot resembling the number 1. Also after the Valiant comic strip "Kelly's Eye" where the eponymous Kelly possessed a magic amulet.} },

   { number:  2,
     nickname: "One little duck.",
     notes: %{From the resemblance of the number 2 to a duck;} },

   { number:  3,
     nickname: "Cup of tea",
     notes: %{} },

   { number:  4,
     nickname: "Knock at the door",
     notes: %{} },

   { number:  5,
     nickname: "Man alive",
     notes: %{} },

   { number:  6,
     nickname: "Tom Mix",
     notes: %{Rhymes with "Six". After Tom Mix, a star of silent-era Westerns} },

   { number:  7,
     nickname: "Lucky",
     notes: %{7 is considered a lucky number in some cultures} },

   { number:  8,
     nickname: "Garden gate",
     notes: %{Rhymes with "Eight"} },

   { number:  9,
     nickname: "Brighton Line",
     notes: %{A reference to the British railway line running from London Victoria and London Bridge to Brighton} },

   { number: 10,
     nickname: "(Boris's) Den",
     notes: %{The name refers to whoever currently resides at Number 10 Downing Street.} },

   { number: 11,
     nickname: "Legs eleven",
     notes: %{A reference to the shape of the number resembling a pair of legs, often chicken legs specifically. The players often wolf whistle in response.} },

   { number: 12,
     nickname: "One dozen",
     notes: %{} },

   { number: 13,
     nickname: "Unlucky for some",
     notes: %{} },

   { number: 14,
     nickname: "The Lawnmower",
     notes: %{The original lawnmower had a 14-inch blade.} },

   { number: 15,
     nickname: "Young and Keen",
     notes: %{Fifteen rhymes with keen} },

   { number: 16,
     nickname: "Never been kissed",
     notes: %{After the song Sweet Sixteen and Never Been Kissed} },

   { number: 17,
     nickname: "Dancing Queen",
     notes: %{ABBA's song Dancing Queen has the number mentioned in the lyrics.} },

   { number: 18,
     nickname: "Coming of Age",
     notes: %{Eighteen is the age of maturity in the UK.} },

   { number: 19,
     nickname: "Goodbye Teens",
     notes: %{Nineteen is the age after which people stop being teenagers.} },

   { number: 20,
     nickname: "Getting Plenty",
     notes: %{Rhymes with "Twenty"} },

   { number: 21,
     nickname: "Key of the Door",
     notes: %{The traditional age of majority.} },

   { number: 22,
     nickname: "Two little ducks",
     notes: %{The numeral 22 resembles the profile of two ducks. Response is often "quack, quack, quack".} },

   { number: 23,
     nickname: "Thee and Me",
     notes: %{Rhymes with 23} },

   { number: 24,
     nickname: "Two dozen",
     notes: %{} },

   { number: 25,
     nickname: "Duck and dive",
     notes: %{Rhymes with "(Twenty) Five", and is made up of a "2" - resembles a duck, and a "5" - resembles an upside-down "2".} },

   { number: 26,
     nickname: "Two and six, half a crown",
     notes: %{Pre-decimalised currency in the UK. Two shillings and sixpence} },

   { number: 27,
     nickname: "Duck and a crutch.",
     notes: %{The number 2 looks like a duck and the number 7 looks like a crutch.} },

   { number: 28,
     nickname: "The Old Braggs",
     notes: %{"the 28th Foot The North Gloucestershire Army Regiment.} },

   { number: 29,
     nickname: "Rise and Shine",
     notes: %{Rhymes with "(Twenty) Nine"} },

   { number: 30,
     nickname: "Burlington Bertie",
     notes: %{Reference to a music hall song of the same name composed in 1900, and a more famous parody (Burlington Bertie from Bow) written in 1915 specifically the line: "I'm Burlington Bertie I rise at ten-thirty".} },

   { number: 31,
     nickname: "Get Up and Run",
     notes: %{Rhymes with "(Thirty) One"} },

   { number: 32,
     nickname: "Buckle My Shoe",
     notes: %{Rhymes with "(Thirty) Two"} },

   { number: 33,
     nickname: "All the threes",
     notes: %{} },

   { number: 34,
     nickname: "Ask for More",
     notes: %{Rhymes with "(Thirty) Four"} },

   { number: 35,
     nickname: "Jump and Jive",
     notes: %{A dance step} },

   { number: 36,
     nickname: "Triple dozen",
     notes: %{3 x 12 = 36} },

   { number: 37,
     nickname: "A flea in heaven",
     notes: %{} },

   { number: 38,
     nickname: "Christmas cake",
     notes: %{Cockney rhyming slang} },

   { number: 39,
     nickname: "Steps",
     notes: %{From the 1935 film 39 Steps by Alfred Hitchcock} },

   { number: 40,
     nickname: "Life Begins",
     notes: %{refers to the saying 'life begins at forty'} },

   { number: 41,
     nickname: "Life’s begun, Time for fun",
     notes: %{} },

   { number: 42,
     nickname: "Winnie the Poo",
     notes: %{} },

   { number: 43,
     nickname: "down on your knees",
     notes: %{This was a phrase that was made popular during wartime by soldiers.} },

   { number: 44,
     nickname: "Droopy drawers",
     notes: %{Rhyme that refers to sagging trousers} },

   { number: 45,
     nickname: "Cowboy's Friend",
     notes: %{a Colt 45 revolver} },

   { number: 46,
     nickname: "Up to tricks",
     notes: %{} },

   { number: 47,
     nickname: "Four and seven",
     notes: %{} },

   { number: 48,
     nickname: "Four Dozen",
     notes: %{} },

   { number: 49,
     nickname: "PC",
     notes: %{Refers to the  1940s / 50s radio show about Police Constable Archibald Berkeley, "The Adventures of PC 49". Usual response is "Evening all".} },

   { number: 50,
     nickname: "Hawaii five oh",
     notes: %{an American 70s police drama} },

   { number: 51,
     nickname: "I love my mum",
     notes: %{} },

   { number: 52,
     nickname: "Danny La Rue",
     notes: %{A reference to Irish drag entertainer Danny La Rue.} },

   { number: 53,
     nickname: "Here comes Herbie",
     notes: %{53 is the racing number of Herbie the VW Beetle. Players may reply "beep beep"!} },

   { number: 54,
     nickname: "Man at the door",
     notes: %{Rhymes with "(Fifty) Four"} },

   { number: 55,
     nickname: "All the fives",
     notes: %{Ged Kelly} },

   { number: 56,
     nickname: "Shotts Bus",
     notes: %{he number 56 bus went from Glasgow to Shotts.} },

   { number: 57,
     nickname: "Heinz Varieties",
     notes: %{Refers to "Heinz 57", the "57 Varieties" slogan of the H. J. Heinz Company.} },

   { number: 58,
     nickname: "Make them wait",
     notes: %{} },

   { number: 59,
     nickname: "The Brighton Line",
     notes: %{5/9 was the price (5 shillings and nine pence)} },

   { number: 60,
     nickname: "Grandma's getting frisky",
     notes: %{} },

   { number: 61,
     nickname: "Baker's bun",
     notes: %{} },

   { number: 62,
     nickname: "Tickety-boo",
     notes: %{an army phrase. possibly originating from the Hindi “tickee babu” meaning “everything’s alright sir”} },

   { number: 63,
     nickname: "Tickle me",
     notes: %{} },

   { number: 64,
     nickname: "Almost retired",
     notes: %{A reference to the former British male age of mandatory retirement - specifically being one year away from it.} },

   { number: 65,
     nickname: "Retirement age, Stop work",
     notes: %{} },

   { number: 66,
     nickname: "Clickety click",
     notes: %{} },

   { number: 67,
     nickname: "Stairway to Heaven",
     notes: %{} },

   { number: 68,
     nickname: "Pick a Mate",
     notes: %{} },

   { number: 69,
     nickname: "Anyway up, Meal for Two, A Favourite of mine",
     notes: %{} },

   { number: 70,
     nickname: "Three Score and Ten",
     notes: %{} },

   { number: 71,
     nickname: "Bang on the Drum",
     notes: %{} },

   { number: 72,
     nickname: "Danny La Rue",
     notes: %{} },

   { number: 73,
     nickname: "Queen Bee. Under The Tree. Lucky 3",
     notes: %{} },

   { number: 74,
     nickname: "Hit the Floor",
     notes: %{} },

   { number: 75,
     nickname: "Granddaddy of Bingo, Lucky Five",
     notes: %{} },

   { number: 76,
     nickname: "Trombones",
     notes: %{} },

   { number: 77,
     nickname: "Two little crutches",
     notes: %{} },

   { number: 78,
     nickname: "39 more steps",
     notes: %{} },

   { number: 79,
     nickname: "Lucky nine",
     notes: %{} },

   { number: 80,
     nickname: "Gandhi's Breakfast",
     notes: %{} },

   { number: 81,
     nickname: "Fat Lady with a walking stick",
     notes: %{} },

   { number: 82,
     nickname: "",
     notes: %{} },

   { number: 83,
     nickname: "Time for Tea",
     notes: %{} },

   { number: 84,
     nickname: "Seven dozen",
     notes: %{} },

   { number: 85,
     nickname: "Staying alive",
     notes: %{} },

   { number: 86,
     nickname: "Between the sticks",
     notes: %{} },

   { number: 87,
     nickname: "Torquay in Devon",
     notes: %{} },

   { number: 88,
     nickname: "Two Fat Ladies",
     notes: %{} },

   { number: 89,
     nickname: "Nearly there",
     notes: %{} },

   { number: 90,
     nickname: "Top of the shop",
     notes: %{} },

].freeze

def all_done
  puts "No more balls. That's it!"
end

def game_ended
  puts "Game finished."
end

def number(int)
  "<%= color('#{int}', :yellow) %>"
end

def nickname(str)
  %{<%= color("#{str}", :bright_blue) %>}
end

cli = HighLine.new

number_of_balls = cli.ask("How many balls in this game?", Integer)
bag = BALLS[0..(number_of_balls - 1)]

cli.say "We are starting a game of <%= color('#{bag.size}', BOLD) %> balls."

loop do
  response = cli.ask('Hit RETURN for the next number or type FINISH to stop playing.')

  break game_ended if response.upcase == 'FINISH'
  break all_done if bag.empty?
  ball = bag.delete(bag.sample)
  puts
  cli.say("<#{nickname(ball[:nickname])}>")
  puts
  cli.say("  -> number #{number(ball[:number])}")
  puts
  cli.say(''.ljust(5) + "(#{ball[:notes]})")
  puts
  puts '-------'
  puts
end
